version: '3.1'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    volumes:
        - spice-db:/var/lib/postgresql
    env_file: spice/local.env
    ports:
    - "5432:5432"
    networks:
      - spice-network

  api:
    build: spice
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./spice:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: spice/local.env
    networks:
        - spice-network

volumes:
    spice-db:
        driver: local
networks:
    spice-network: